Information:
  Title: PlOszukiwacz's Blog
  Icon: icon.png
  Description: PlOszukiwacz's Blog
  Link: github.com/PlOszukiwaczDEV/blog
  Theme: CatppuccinMocha

Connections:
  GitHub: PlOszukiwaczDEV
  GitLab: 
  Bluesky: ploszukiwacz.bsky.social
  Twitter: ploszukiwacz
  Mastodon: ploszukiwacz
  Medium:
  Twitch: ploszukiwacz
  YouTube: realploszukiwacz
