Information:
  Title: PlOszukiwacz's Blug
  Icon: icon.png
  Description: PlOszukiwacz's Blog
  Link: github.com/PlOszukiwaczDEV/blog
  Theme: Default

Connections:
  GitHub: PlOszukiwaczDEV
  GitLab: 
  Bluesky:
  Twitter:
  Mastodon:
  Medium:
  Twitch:
  YouTube:
